# mybatis配置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.myinfo.base.entity
spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/myinfo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&noAccessToProcedureBodies=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-active: 500
    max-idle: 100
    max-wait: 10000
    maximum-pool-size: 200
    min-idle: 30
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    validation-query: select 1
  jpa:
    show-sql: true
  # 缓存
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    pool:
      max-active: -1
      max-idle: 20
      max-wait: -1
      min-idle: 20
    port: 6379
    timeout: 30000
